"""Build a deployable copy of the web page in dist/, with config.js pointing at the backend in API_BASE_URL.

Run it from any directory, for example:
    API_BASE_URL=https://calorie-calendar-api.onrender.com python3 scripts/build_frontend.py
Netlify and Vercel can run the same command as their build step, with dist as the publish/output directory.
"""

import json
import os
import re
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
FRONTEND_DIR = PROJECT_ROOT / "frontend"
OUTPUT_DIR = PROJECT_ROOT / "dist"
API_BASE_URL_ENV_VAR = "API_BASE_URL"
# A scheme and host, optionally followed by a path, like https://calorie-calendar-api.onrender.com
URL_PATTERN = re.compile(r"https?://[^/\s]+(/\S*)?")


def main() -> int:
    # app.js appends paths such as /search-food, so drop any trailing slash.
    api_base_url = os.environ.get(API_BASE_URL_ENV_VAR, "").strip().rstrip("/")
    if not URL_PATTERN.fullmatch(api_base_url):
        print(
            f"Set {API_BASE_URL_ENV_VAR} to the backend's URL, like https://calorie-calendar-api.onrender.com",
            file=sys.stderr,
        )
        return 1

    OUTPUT_DIR.mkdir(exist_ok=True)
    # Clear the previous build, but keep dot-folders such as .vercel, where host CLIs remember the linked project.
    for entry in OUTPUT_DIR.iterdir():
        if entry.name.startswith("."):
            continue
        if entry.is_dir():
            shutil.rmtree(entry)
        else:
            entry.unlink()
    shutil.copytree(FRONTEND_DIR, OUTPUT_DIR, dirs_exist_ok=True)

    config = {"apiBaseUrl": api_base_url}
    (OUTPUT_DIR / "config.js").write_text(
        f"// Generated by scripts/build_frontend.py from {API_BASE_URL_ENV_VAR}.\n"
        f"window.calorieCalendarConfig = {json.dumps(config)};\n"
    )
    print(f"Built {OUTPUT_DIR} for the backend at {api_base_url}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
